### ISSUE TITLE
Creality CP-01 

### ISSUE THREAD

**Issue by CyberLele** [capekoviroboti/creality-dwin-lcd-customizer#1]
Hello, I have a creality CP-01 with lcd dmt48270c043_06wt and creality V2.5.2 board, I'm trying to install this program and make it work so that I can finally update Marlin 1.1.6 of creality with the latest available.. But with Windows 11 I'm having big problems, I install python 3.7 to avoid installation problems but still requires me to install the 3.10 from Microsoft store, with the consequent compatibility problems .. Any tips or suggestions? Thank you

**Comment by capekoviroboti** [comment]
Hi @CyberLele! I have not finished getting this working on Windows yet, as I only have *nix machines so I can't test things out. But if your main goal is to get Marlin to 2.0.9.3, without customizing the screen firmware I can help you do that.

You will want to head over to the Marlin project on GitHub and download the latest code there: https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.9.3

Then head to the configuration files from Marlin and download the latest ones from there: https://github.com/MarlinFirmware/Configurations/releases/tag/2.0.9.3

Extract those .zip files. In the Configurations folder, find your printer and board combo and copy the .h files from their into the Marlin/Marlin folder.

Then install VSCode, then the Autobuild Marlin and Platformio plugins for VSCode. Open up the Marlin folder, go to the Autobuild Marlin tab and press build. That should create the firmware binary file you need.

**Comment by CyberLele** [comment]
@capekoviroboti Thanks, building marlin is not a problem, what is missing is to make the lcd work! Yesterday I managed to make the program work with python 3.7, but in the "custom" section it is not possible to build the firmware. So I tried with CR6, the lcd files are created, but it generates errors at the time of compilation. As soon as I finish working I share the report

**Comment by capekoviroboti** [comment]
Can you copy over the text of the errors you are seeing?

**Comment by CyberLele** [comment]
> From cmd or powershell

- Exception in thread Thread-3:
- Traceback (most recent call last):
-   File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner    self.run()
-   File "C:\Program Files\Python37\lib\threading.py", line 865, in run     self._target(*self._args, **self._kwargs)
-   File "C:\Program Files\Python37\lib\site-packages\gooey\gui\processor.py", line 70, in _forward_stdout _progress = self._extract_progress(line)
- File "C:\Program Files\Python37\lib\site-packages\gooey\gui\processor.py", line 84, in _extract_progress find = partial(re.search, string=text.strip().decode(self.encoding))
- UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 53: invalid start byte`


> From application

- Cleaning up any existing files in directory C:\Users\Gabriele\Downloads\creality-dwin-lcd-customizer-master\creality-dwin-lcd-customizer-master\DWIN_SET_MOD\DWIN_SET
- Copying baseline files from C:\Users\Gabriele\Downloads\creality-dwin-lcd-customizer-master\creality-dwin-lcd-customizer-master\DWIN_SET into C:\Users\Gabriele\Downloads\creality-dwin-lcd-customizer-master\creality-dwin-lcd-customizer-master\DWIN_SET_MOD\DWIN_SET
- Setting the bootscreen image for CR6 printers is currently unsupported
- Using the 'Default' color scheme
- Copying from C:\Users\Gabriele\Downloads\creality-dwin-lcd-customizer-master\creality-dwin-lcd-customizer-master\color-schemes\Default
- Using language: English
- Compiling mainboard firmware
- Calling script with `powershell -executionpolicy bypass -noexit "& "{MBS_FULL_PATH}" -m D:\Creality CP-01\FIRMWARE\Marlin\test\2.0.x\Marlin -e mega2560`
